# Generated by Django 4.0.3 on 2022-04-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Accused name')),
                ('father_name', models.CharField(max_length=500, verbose_name='father name')),
                ('alias', models.CharField(max_length=500, verbose_name='Accused alias')),
                ('address', models.CharField(max_length=100, verbose_name='Accuse address')),
                ('nic', models.CharField(max_length=1000, unique=True, verbose_name='Accused NIC')),
                ('gender', models.CharField(max_length=10, verbose_name='Accused gender')),
                ('dob', models.DateField(verbose_name='Accused Date of birth')),
                ('status', models.IntegerField(choices=[(0, 'Arrested'), (1, 'Escaped'), (2, 'Bailed'), (3, 'Released')], default=0, verbose_name='Accused status')),
                ('contact', models.CharField(max_length=20, verbose_name='Accused contact')),
                ('phone', models.CharField(max_length=20, verbose_name='Accused phone')),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.URLField(verbose_name='image of the accused')),
            ],
            options={
                'db_table': 'accused',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='InvestigationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Officer Name')),
                ('dob', models.DateField(verbose_name='Officer Date of birth')),
                ('rank', models.IntegerField()),
                ('contacts', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'investigation-officer',
            },
        ),
        migrations.CreateModel(
            name='Petitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('father_name', models.CharField(max_length=500)),
                ('address', models.TextField(default='', max_length=1500)),
                ('contact', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'petitioner',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name="Victim's name")),
                ('father_name', models.CharField(max_length=500, verbose_name="Victim's father")),
                ('address', models.CharField(max_length=500, verbose_name="Victim's address")),
                ('contact', models.CharField(max_length=30, verbose_name="Victim's contact")),
                ('nic', models.CharField(max_length=50, unique=True, verbose_name="Victim's nic")),
            ],
            options={
                'db_table': 'victim',
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lodged', models.DateTimeField()),
                ('complaint', models.TextField(max_length=10000)),
                ('accused', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.accused')),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.incident')),
                ('petitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.petitioner')),
            ],
            options={
                'db_table': 'fir',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_section', models.TextField()),
                ('case_status', models.CharField(max_length=100, verbose_name='case status')),
                ('case_detail', models.TextField(max_length=10000)),
                ('FIR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fir')),
                ('investigation_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.investigationofficer')),
            ],
            options={
                'db_table': 'case',
            },
        ),
    ]
