# Generated by Django 4.0.3 on 2022-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_petitioner_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accused',
            name='nic',
            field=models.CharField(max_length=1000, verbose_name='Accused NIC'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='nic',
            field=models.CharField(max_length=50, verbose_name="Victim's nic"),
        ),
    ]
